dist: bionic
os: linux
language: python
cache: pip
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
stages:
  - lint
  - test
  - integration
jobs:
  include:
    - stage: lint
      python: 3.6
      env: TOXENV=lint
    - stage: integration
      services:
        - xvfb
      python: 3.6
      addons:
        firefox: latest
        apt:
          packages: firefox-geckodriver
      env:
        - USE_SELENIUM=1
        - MOZ_HEADLESS=1
      script:
        - tox -v
  allow_failures:
    - stage: integration

install:
  - pip install tox tox-travis codecov

script:
  - tox -v

after_success:
  #- coverage combine
  - codecov
